# Generated by Django 2.1.8 on 2021-08-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pcap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nth', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='data published')),
            ],
        ),
    ]
