# Generated by Django 2.1.8 on 2021-09-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_collect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcap',
            name='nth',
        ),
        migrations.AddField(
            model_name='pcap',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
