# Generated by Django 2.1.8 on 2021-09-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlsres',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
