# Generated by Django 2.2 on 2021-09-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_test', '0003_flowres'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('result', models.CharField(default='none', max_length=10)),
            ],
        ),
    ]
