# Generated by Django 2.1.8 on 2021-08-31 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flow_cut', '0002_auto_20210831_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='tls_feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_hello', models.CharField(max_length=120)),
                ('server_hello', models.CharField(max_length=120)),
                ('certificate', models.CharField(max_length=120)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow_cut.Pcaps_cut')),
            ],
        ),
    ]
