# Generated by Django 2.1.8 on 2021-08-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extract', '0002_auto_20210831_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='tls_feature',
            name='label',
            field=models.CharField(default='white', max_length=10),
        ),
    ]
