# Generated by Django 2.1.8 on 2021-08-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extract', '0003_tls_feature_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tls_feature',
            name='certificate',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='tls_feature',
            name='client_hello',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='tls_feature',
            name='server_hello',
            field=models.CharField(max_length=3000),
        ),
    ]
