# Generated by Django 2.1.8 on 2021-09-07 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow_cut', '0005_auto_20210907_0852'),
        ('feature_extract', '0006_auto_20210903_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='tls_feature',
            name='test_name',
            field=models.ForeignKey(default='error', on_delete=django.db.models.deletion.CASCADE, to='flow_cut.Pcaps_cut'),
        ),
    ]
