# Generated by Django 3.2.7 on 2021-09-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extract', '0006_auto_20210903_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tls_feature',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
