# Generated by Django 2.2 on 2021-09-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extract', '0006_auto_20210903_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='flow_featue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=100)),
                ('label', models.CharField(default='white', max_length=10)),
                ('feature', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='image_featue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=100)),
                ('label', models.CharField(default='white', max_length=10)),
                ('feature', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='tls_feature',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
