# Generated by Django 2.1.8 on 2021-09-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extract', '0007_tls_feature_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tls_feature',
            name='test_name',
        ),
    ]
