# Generated by Django 2.1.8 on 2021-09-07 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extract', '0008_remove_tls_feature_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tls_feature',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow_cut.Pcaps_cut'),
        ),
    ]
