# Generated by Django 2.1.8 on 2021-09-07 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extract', '0009_auto_20210907_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tls_feature',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow_cut.Pcaps_cut', to_field='name'),
        ),
    ]
