# Generated by Django 2.1.8 on 2021-08-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pcaps_cut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('nth', models.IntegerField()),
            ],
        ),
    ]
