# Generated by Django 2.1.8 on 2021-08-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_cut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcaps_cut',
            name='label',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='pcaps_cut',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
