# Generated by Django 2.1.8 on 2021-09-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_cut', '0003_auto_20210907_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcaps_cut',
            name='label',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
