# Generated by Django 2.1.8 on 2021-09-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_cut', '0004_pcaps_cut_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcaps_cut',
            old_name='original',
            new_name='origin',
        ),
        migrations.AddField(
            model_name='pcaps_cut',
            name='type',
            field=models.CharField(default='flow', max_length=20),
        ),
    ]
