# Generated by Django 2.2 on 2021-09-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_cut', '0005_auto_20210907_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcaps_cut',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
