# Generated by Django 2.1.8 on 2021-09-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_cut', '0005_auto_20210907_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcaps_cut',
            name='id',
        ),
        migrations.AlterField(
            model_name='pcaps_cut',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
