# Generated by Django 2.2 on 2021-09-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_cut', '0006_auto_20210914_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='pcap_cut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('origin', models.CharField(default='wrong', max_length=100)),
                ('label', models.CharField(default='test', max_length=100)),
                ('type', models.CharField(default='flow', max_length=20)),
            ],
        ),
    ]
